src/Entity/Language.php
<?php

namespace App\Entity;

use App\Repository\LanguageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LanguageRepository::class)]
class Language
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 8)]
    private ?string $iso_code = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTime $created = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $updated = null;

    /**
     * @var Collection<int, Origin>
     */
    #[ORM\OneToMany(targetEntity: Origin::class, mappedBy: 'language')]
    private Collection $origins;

    /**
     * @var Collection<int, Translation>
     */
    #[ORM\OneToMany(targetEntity: Translation::class, mappedBy: 'language')]
    private Collection $translations;

    public function __construct()
    {
        $this->origins = new ArrayCollection();
        $this->translations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsoCode(): ?string
    {
        return $this->iso_code;
    }

    public function setIsoCode(string $iso_code): static
    {
        $this->iso_code = $iso_code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    public function setCreated(\DateTime $created): static
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTime
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTime $updated): static
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * @return Collection<int, Origin>
     */
    public function getOrigins(): Collection
    {
        return $this->origins;
    }

    public function addOrigin(Origin $origin): static
    {
        if (!$this->origins->contains($origin)) {
            $this->origins->add($origin);
            $origin->setLanguage($this);
        }

        return $this;
    }

    public function removeOrigin(Origin $origin): static
    {
        if ($this->origins->removeElement($origin)) {
            // set the owning side to null (unless already changed)
            if ($origin->getLanguage() === $this) {
                $origin->setLanguage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Translation>
     */
    public function getTranslations(): Collection
    {
        return $this->translations;
    }

    public function addTranslation(Translation $translation): static
    {
        if (!$this->translations->contains($translation)) {
            $this->translations->add($translation);
            $translation->setLanguage($this);
        }

        return $this;
    }

    public function removeTranslation(Translation $translation): static
    {
        if ($this->translations->removeElement($translation)) {
            // set the owning side to null (unless already changed)
            if ($translation->getLanguage() === $this) {
                $translation->setLanguage(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Übersetzungs-App erstellt mit Symfony 7</title>
        <link href="{{ asset('css/adminlte.min.css') }}" rel="stylesheet" />
        {% block javascript %}{% endblock %}
    </head>
    <body class="dark-mode">
        {% block content %}{% endblock %}
    </body>
</html>

templates/list.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<div class="card">
    <div class="card-body table-responsive">
        <table class="table table-hover">
            <thead>
            <tr class="row">
                <th class="col-1">ID</th>
                <th class="col-7">Text</th>
                <th class="col-1">Erstellt am</th>
                <th class="col-2">Übersetzungen</th>
                <th class="col-1"></th>
            </tr>
            </thead>
            <tbody>
            {% for origin in origins %}
                <tr class="row">
                    <td class="col-1">{{ origin.id }}</td>
                    <td class="col-7">{{ origin.txt }}</td>
                    <td class="col-1">{{ origin.created|date("d.m.Y H:i") }}</td>
                    <td class="col-2">
                        {% for transl in origin.translations %}
                            <img src="{{ asset('img/' ~ transl.language.isoCode ~ '.png') }}" />
                        {% endfor %}
                    </td>
                    <td class="col-1"><a href="{{ path('origin', {'id': origin.id}) }}" class="btn btn-sm btn-info float-left bg-olive">übersetzen</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="card-footer clearfix">
        <a href="{{ path('origin_new') }}" class="btn btn-sm btn-info float-left">Neu</a>
    </div>
</div>
{% endblock %}

templates/new.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h1>Neuen Text erstellen</h1>
            <p>Neue Texte werden automatisch der deutschen Sprache zugewiesen.</p>
            {{ form(form) }}
        </div>
        <div class="card-footer clearfix">
            <a href="{{ path('list') }}" class="btn btn-sm btn-info float-left">Zurück</a>
        </div>
    </div>
{% endblock %}

templates/origin.html.twig
{% extends 'base.html.twig' %}

{% block javascript %}
    <script src="{{ asset('js/translate.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            {% if origin %}
                <h1>Übersetzung erstellen</h1>
                <blockquote class="quote-olive">
                    <p>{{ origin.txt }}</p>
                    <small>
                        <p>{{ origin.created|date("d.m.Y H:i") }}</p>
                    </small>
                </blockquote>

                {% if form %}
                    {{ form_start(form) }}
                        <div id="translation">
                            <div class="mb-3">
                                {{ form_label(form.language) }}
                            </div>
                            <div class="mb-3">
                                {{ form_widget(form.language) }}
                            </div>
                            {{ form_row(form.translation) }}
                            {{ form_row(form.origin_id) }}
                            {{ form_row(form.translate) }}
                            {{ form_row(form.save) }}
                        </div>
                    {{ form_end(form) }}
                {% endif %}
            {% else %}
                <p>Kein Text gefunden</p>
            {% endif %}
        </div>
        <div class="card-footer clearfix">
            <a href="{{ path('list') }}" class="btn btn-sm btn-info float-left">Zurück</a>
        </div>
    </div>
{% endblock %}